{% set name = "emcee" %}
{% set version = "3.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/emcee-{{ version }}.tar.gz
  sha256: 11af4daf6ab8f9ca69681e3c29054665db7bbd87fd4eb8e437d2c3a1248c637d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=40.6.0
    - setuptools-scm
    - wheel
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - emcee
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://emcee.readthedocs.io
  summary: The Python ensemble sampling toolkit for MCMC
  dev_url: https://github.com/dfm/emcee
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - dfm
    - danielballan
