{% set version = "3.0.0" %}

package:
  name: emcee
  version: {{ version }}

source:
  fn: emcee-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/e/emcee/emcee-{{ version }}.tar.gz
  md5: 4424318732c500a1d4db1b71e3eea7cf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - emcee

about:
  home: http://dan.iel.fm/emcee/
  license: MIT
  summary: 'Kick ass affine-invariant ensemble MCMC sampling'

extra:
  recipe-maintainers:
    - ericdill
    - tacaswell
    - licode
    - dfm
    - danielballan
